### ISSUE TITLE
Interface doesn't render properly: Missing "resources.qwartz.de/css/basic1.css"

### ISSUE THREAD

**Issue by jackmulholland** [drinking-code/g2-continuity-corner-generator#1]
From https://resources.qwartz.de/css/basic1.css [Error] Failed to load resource: (basic1.css, line 0)

interface doesn't render properly

**Comment by drinking-code** [comment]
Oh, ya, that domain is long down. I just made the repo with the css file public:
https://github.com/drinking-code/qwartz_resources/blob/master/css/basic1.css
